#! /bin/sh

#
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#

# Network manager
#nm-applet &

# edit with monitor names: "xrandr --listactivemonitors"
xrandr --output DP-1 --right-of HDMI-0

xsetroot -cursor_name left_ptr
sxhkd &
picom --experimental-backends &
picom --backend glx &
nitrogen --restore
wmname LG3D &
lxpolkit &
xset -dpms s off & # disable screen blanking
dunst &

# Swallow

#nohup pidof $HOME/.scripts/bspswallow || $HOME/.scripts/bspswallow &
pgrep bspswallow || nohup ~/.scripts/bspswallow &

bspc monitor HDMI-0 -d 一
bspc monitor DP-1 -d 二 三 四 五 六 七 八 九 十

# Use this instead of the above for a single monitor setup
# bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# Workspaces

bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
#$HOME/.config/bspwm/autostart

# Default state/workspace for applications
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'scrcpy' state=floating center=true
bspc rule -a 'pavucontrol' state=floating rectangle=700x800+0+0 center=true
bspc config pointer_modifier mod4
bspc config focus_follows_pointer true

bspc config border_width 7
bspc config focused_border_color "#daa6ca"
bspc config normal_border_color "#282e3a"

sleep 0.69

# Autostart applications:

# Start Polybar
$HOME/.config/polybar/scripts/launch-polybar.sh &
